param(
  [string]$BannerlordRoot = "C:\Program Files (x86)\Steam\steamapps\common\Mount & Blade II Bannerlord",
  [string]$DestinationRoot = "$HOME\Documents\bannerlord-rot-hot-export",
  [string[]]$ModModules = @(),
  [switch]$IncludeAllXml,
  [switch]$SkipCoreModules,
  [switch]$NoZip
)

$ErrorActionPreference = "Stop"

function Copy-XmlFilesForModule {
  param(
    [string]$ModuleName,
    [string]$ModulePath,
    [string]$Destination,
    [bool]$IncludeAllXmlFiles
  )

  $targetModulePath = Join-Path -Path $Destination -ChildPath $ModuleName
  New-Item -ItemType Directory -Force -Path $targetModulePath | Out-Null

  if ($IncludeAllXmlFiles) {
    $xmlFiles = Get-ChildItem -Path $ModulePath -Recurse -Filter "*.xml" -File
  } else {
    $moduleData = Join-Path -Path $ModulePath -ChildPath "ModuleData"
    $subModule = Join-Path -Path $ModulePath -ChildPath "SubModule.xml"

    $xmlFiles = @()

    if (Test-Path $moduleData) {
      $xmlFiles += Get-ChildItem -Path $moduleData -Recurse -Filter "*.xml" -File
    }

    if (Test-Path $subModule) {
      $xmlFiles += Get-Item $subModule
    }
  }

  foreach ($file in $xmlFiles) {
    $relativePath = $file.FullName.Substring($ModulePath.Length).TrimStart("\")
    $targetPath = Join-Path -Path $targetModulePath -ChildPath $relativePath
    $targetDir = Split-Path -Path $targetPath -Parent

    New-Item -ItemType Directory -Force -Path $targetDir | Out-Null
    Copy-Item -Path $file.FullName -Destination $targetPath -Force

    [PSCustomObject]@{
      module = $ModuleName
      relative_path = $relativePath
      source_path = $file.FullName
      bytes = $file.Length
      last_write_time = $file.LastWriteTime.ToString("s")
    }
  }
}

if (-not (Test-Path $BannerlordRoot)) {
  throw "Bannerlord root not found: $BannerlordRoot"
}

$modulesRoot = Join-Path -Path $BannerlordRoot -ChildPath "Modules"

if (-not (Test-Path $modulesRoot)) {
  throw "Bannerlord Modules folder not found: $modulesRoot"
}

$timestamp = Get-Date -Format "yyyyMMdd_HHmmss"
$exportName = "rot_hot_xml_export_$timestamp"
$destination = Join-Path -Path $DestinationRoot -ChildPath $exportName

New-Item -ItemType Directory -Force -Path $destination | Out-Null

$coreModules = @("Native", "Sandbox", "SandboxCore", "StoryMode")

$allModuleDirs = Get-ChildItem -Path $modulesRoot -Directory | Sort-Object Name

if ($ModModules.Count -eq 0) {
  $autoDetected = $allModuleDirs | Where-Object {
    $_.Name -match "(?i)(realm|thrones|rot|hot|dragon|house)"
  } | Select-Object -ExpandProperty Name

  $ModModules = @($autoDetected)
}

if ($ModModules.Count -eq 0) {
  Write-Host ""
  Write-Warning "No RoT/HOT-like module was auto-detected."
  Write-Host "Available modules:"
  $allModuleDirs | ForEach-Object { Write-Host "  $($_.Name)" }
  Write-Host ""
  throw "Pass the module name explicitly, e.g. -ModModules @('RealmOfThrones')"
}

$modulesToExport = @()

if (-not $SkipCoreModules) {
  $modulesToExport += $coreModules
}

$modulesToExport += $ModModules
$modulesToExport = $modulesToExport | Select-Object -Unique

Write-Host ""
Write-Host "===================================="
Write-Host " RoT / HOT XML Export"
Write-Host "===================================="
Write-Host "BannerlordRoot: $BannerlordRoot"
Write-Host "Destination: $destination"
Write-Host "IncludeAllXml: $IncludeAllXml"
Write-Host "Modules:"
$modulesToExport | ForEach-Object { Write-Host "  $_" }
Write-Host ""

$manifestRows = @()

foreach ($module in $modulesToExport) {
  $modulePath = Join-Path -Path $modulesRoot -ChildPath $module

  if (-not (Test-Path $modulePath)) {
    Write-Warning "Module not found, skipping: $modulePath"
    continue
  }

  Write-Host "Exporting module: $module"
  $manifestRows += Copy-XmlFilesForModule `
    -ModuleName $module `
    -ModulePath $modulePath `
    -Destination $destination `
    -IncludeAllXmlFiles ([bool]$IncludeAllXml)
}

$manifestPath = Join-Path -Path $destination -ChildPath "export_manifest.csv"
$manifestRows | Export-Csv -Path $manifestPath -NoTypeInformation -Encoding UTF8

$summaryPath = Join-Path -Path $destination -ChildPath "README_EXPORT.txt"
$summary = @"
RoT / HOT XML export
Generated: $(Get-Date -Format s)
BannerlordRoot: $BannerlordRoot
Destination: $destination
IncludeAllXml: $IncludeAllXml
SkipCoreModules: $SkipCoreModules
Modules:
$($modulesToExport -join "`r`n")

Upload the ZIP generated by this script to the analysis chat.
"@
$summary | Out-File -FilePath $summaryPath -Encoding UTF8

$fileCount = ($manifestRows | Measure-Object).Count
Write-Host ""
Write-Host "XML files copied: $fileCount"
Write-Host "Manifest: $manifestPath"

if (-not $NoZip) {
  $zipPath = "$destination.zip"

  if (Test-Path $zipPath) {
    Remove-Item $zipPath -Force
  }

  Compress-Archive -Path (Join-Path -Path $destination -ChildPath "*") -DestinationPath $zipPath -Force
  Write-Host "ZIP: $zipPath"
}

Write-Host ""
Write-Host "Export complete."
Write-Host ""
Write-Host "Next step: upload the ZIP to the RoT analysis chat."
